sudo: required

language: python
python:
  - "3.6"

services:
  - docker

install: pip install -r requirements.txt

## Add later to include tests
#script: python -m pytest --cov=website/ tests/

before_deploy:
    - docker build -t michaelvanvliet/container-data-analysis:latest .

deploy:
    provider: script
    script: dockerhub_deploy.sh
    on:

tags: true